[tool]
[tool.poetry]
name = "Userator_Deployer"
version = "1.0"
description = "Automatic Deploy Userator to Heroku"
authors = ["DucTheVulpe <@DucTheVulpe>"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
